### PR TITLE
Add annotations for module.exports.

### PR DESCRIPTION
**Pull request by RoySegall**
#3

### CODE REVIEW

**Comment by backhand** [comment]
Thanks for the PR, you need to make sure the tests are passing though.

**Comment by RoySegall** [comment]
Yes. Although I don't know what's the problem :\

**Comment by backhand** [comment]
If you look in the data/testfile.js there are now two module.exports statements. One overrides the other, I would start there.

**Comment by RoySegall** [comment]
HMMM... I can see what you saying. I could create another file and parse it so we would avoid collision.

Is that sound's OK?

**Comment by RoySegall** [comment]
@backhand Ready for another review. The tests are green now.

10x.

**Comment by RoySegall** [comment]
@backhand Any new?

**Comment by backhand** [comment]
Just back from vacation today, but lgtm so will accept it.

**Pull request merged**
